### ISSUE TITLE
--lf and --ipdb means pytest-cache does not get populated. 

### ISSUE THREAD

**Issue by suederat** [mverteuil/pytest-ipdb#32]
with a prior run 1 failure and a 2 pass in test_foo.py 
then run with 
py.test --ipdb -s --lf test/test_foo.py
and all tests are run instead of single prior failure.

pip freeze|grep py
MySQL-python==1.2.3
ipython==2.3.0
libxml2-python==2.6.30
p4python==2014.1.898721
py==1.4.26
pycrypto==2.3
pyflakes==0.8
pylogsparser==1.2
pyserial==2.6
pytest==2.6.4
pytest-cache==1.0
pytest-ipdb==0.1-prerelease2
python-dateutil==1.5
python-ldap==2.4.12
pytz==2013.8
vcrpy==1.1.2

**Comment by mverteuil** [comment]
Please see the README: this project has been end-of-lifed.

I recommend that you use pdbpp as an easier and better alternative:
https://pypi.python.org/pypi/pdbpp/
