### ISSUE TITLE
Add sdist package

### ISSUE THREAD

**Issue by fizyk** [mverteuil/pytest-ipdb#7]
Hey,

Would it be possible to get source (sdist) distribution uploaded into pypi apart from egg files? Would help to beeing ableto install apckage through pip, as it doesn't work with eggs at the moment.

**Comment by mverteuil** [comment]
Please see the README: this project has been end-of-lifed.

I recommend that you use pdbpp as an easier and better alternative:
https://pypi.python.org/pypi/pdbpp/
