### ISSUE TITLE
pytest-ipdb not installable via pip

### ISSUE THREAD

**Issue by joar** [mverteuil/pytest-ipdb#9]
Trying to install pytest-ipdb via pip gives me the following error:
<pre>(clientsite)➜  clientsite git:(master) ✗ pip -vvv install pytest-ipdb
Downloading/unpacking pytest-ipdb
  Getting page https://pypi.python.org/simple/pytest-ipdb/
  URLs to search for versions for pytest-ipdb:
  * https://pypi.python.org/simple/pytest-ipdb/
  Analyzing links from page https://pypi.python.org/simple/pytest-ipdb/
    Skipping link https://pypi.python.org/packages/2.6/p/pytest-ipdb/pytest_ipdb-0.1_prerelease-py2.6.egg#md5=2aec77da8f802ebc2186a8252ee65161 (from https://pypi.python.org/simple/pytest-ipdb/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/p/pytest-ipdb/pytest_ipdb-0.1_prerelease-py2.7.egg#md5=22bf8a4f1ee9267a5f1fe8a18ce1a1e4 (from https://pypi.python.org/simple/pytest-ipdb/); unknown archive format: .egg
  Could not find any downloads that satisfy the requirement pytest-ipdb
No distributions at all found for pytest-ipdb
Exception information:
Traceback (most recent call last):
  File "/home/joar/virtualenvs/clientsite/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/home/joar/virtualenvs/clientsite/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/joar/virtualenvs/clientsite/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1026, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/joar/virtualenvs/clientsite/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/index.py", line 171, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for pytest-ipdb

Storing complete log in /home/joar/.pip/pip.log
</pre>

The issue seems to be that .egg archives [are not supported by pip](https://github.com/pypa/pip/issues/334)

**Comment by mverteuil** [comment]
Please see the README: this project has been end-of-lifed.

I recommend that you use pdbpp as an easier and better alternative:
https://pypi.python.org/pypi/pdbpp/
